const uploadFileTypes = {
    SET_FILES_UPLOAD: "SET_FILES_UPLOAD",
    SET_UPLOAD_PROGRESS: "SET_UPLOAD_PROGRESS",
    SET_SUCCESS_UPLOAD_FILE: "SET_SUCCESS_UPLOAD_FILE",
    SET_FAILURE_UPLOAD_FILE: "SET_FAILURE_UPLOAD_FILE",
    SET_REMOVE_FILE: "SET_REMOVE_FILE"
};

export default uploadFileTypes;